spring:
  application:
    name: payment-service
    
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        register-health-check: false
        instance-id: ${spring.application.name}:${random.int[1,9999]}


    stream:
      function:
        definition : paymentProcessor
      bindings:
        paymentProcessor-in-0 :
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event


server:
  port: 0