spring:
  application:
    name: userorder-aggregator-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        register-health-check: false
        instance-id: ${spring.application.name}:${random.int[1,9999]}
  
  
    stream:
      function:
        definition: orderEventConsumer # Name of the bean method
      bindings:
        orderEventConsumer-in-0:
          destination: order-event

          
          
server:
  port: 0