spring:
  cloud:
    stream:
      function:
        definition: consumOrderCompleteEvent # Name of the bean method
      bindings:
        consumOrderCompleteEvent-in-0: 
          destination: order-event

          
          
server:
  port: 8084