spring:
  application:
    name: order-service
    
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        register-health-check: false
        instance-id: ${spring.application.name}:${random.int[1,9999]}


    stream:
      function:
        definition: orderSupplier;paymentEventConsumer # Name of the bean method
      bindings:
        orderSupplier-out-0: # function definition bean method name - out - a number. OUT because we are publishing an event to 'order-event' topic
          destination: order-event
        paymentEventConsumer-in-0: # IN because we are consuming an event from 'payment-event' topic
          destination: payment-event

          
          
server:
  port: 8081