server:
  port: 8082


  
  
spring:
  application:
    name: service-b

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000            
      
     
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        register-health-check: false
        instance-id: ${spring.application.name}:${random.int[1,9999]}

