server:
  port: 8083
  
  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          
          

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          security: TRACE
          client:
            RestTemplate: TRACE